package es.academia.modelo;

// Generated 21-jul-2014 23:03:01 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.apache.log4j.Logger;
import org.hibernate.Query;
import org.hibernate.Session;

import es.academia.modelo.AbstractModelObject;
import es.academia.utils.ACALog;

/**
 * Alumno generated by hbm2java
 */ 
public class Alumno extends AbstractModelObject implements java.io.Serializable {
 
	/**
	 * 
	 */
	private static final Logger log = ACALog.getLogger(Alumno.class);
	
	private static final long serialVersionUID = -4396334510288034564L;
	private Integer idAlumno;
	private Integer conocimiento;
	private String nombre;
	private String apellidos;
	private String nif;
	private Date FNacimiento;
	private String direccion;
	private String poblacion;
	private String provincia;
	private String cp;
	private String telFijo;
	private String telMovil;
	private String telMovil2;
	private String EMail;
	private String nombreTutor;
	private String apellidosTutor;
	private String niftutor;
	private Date FAlta;
	private Date FBaja;
	private String baja;
	private String indExportado;
	private String notas;
	private Set<Matricula> matriculas = new HashSet<Matricula>();  

	public Alumno() {
	}

	public Alumno(int conocimiento) {
		this.conocimiento = conocimiento;
	}

	public Alumno(Integer conocimiento, String nombre, String apellidos,
			String nif, Date FNacimiento, String direccion, String poblacion,
			String provincia, String cp, String telFijo, String telMovil,String telMovil2,
			String EMail, String nombreTutor, String apellidosTutor,
			String niftutor, Date FAlta, Date FBaja, String baja,
			String indExportado, String notas, Set<Matricula> matriculas) {
		this.conocimiento = conocimiento;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.nif = nif;
		this.FNacimiento = FNacimiento;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.provincia = provincia;
		this.cp = cp;
		this.telFijo = telFijo;
		this.telMovil = telMovil;
		this.telMovil2 = telMovil2;
		this.EMail = EMail;
		this.nombreTutor = nombreTutor;
		this.apellidosTutor = apellidosTutor;
		this.niftutor = niftutor;
		this.FAlta = FAlta;
		this.FBaja = FBaja;
		this.baja = baja;
		this.indExportado = indExportado;
		this.notas = notas;
		this.matriculas = matriculas;
	}

	public Integer getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(Integer idAlumno) {
		firePropertyChange("idAlumno", this.idAlumno, idAlumno);
		this.idAlumno = idAlumno;
	}

	public Integer getConocimiento() {
		return this.conocimiento;
	}

	public void setConocimiento(Integer conocimiento) {
		firePropertyChange("conocimiento", this.conocimiento, conocimiento);
		this.conocimiento = conocimiento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		firePropertyChange("nombre", this.nombre, nombre);
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		firePropertyChange("apellidos", this.apellidos, apellidos);
		this.apellidos = apellidos;
	}
	
	public String getNombreCompleto(){
		return getNombre() +" " +getApellidos();
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		firePropertyChange("nif", this.nif, nif);
		this.nif = nif;
	}

	public Date getFNacimiento() {
		return this.FNacimiento;
	}

	public void setFNacimiento(Date FNacimiento) {
		firePropertyChange("FNacimiento", this.FNacimiento, FNacimiento);
		this.FNacimiento = FNacimiento;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		firePropertyChange("direccion", this.direccion, direccion);
		this.direccion = direccion;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		firePropertyChange("poblacion", this.poblacion, poblacion);
		this.poblacion = poblacion;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		firePropertyChange("provincia", this.provincia, provincia);
		this.provincia = provincia;
	}

	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		firePropertyChange("cp", this.cp, cp);
		this.cp = cp;
	}

	public String getTelFijo() {
		
		return this.telFijo;
	}

	public void setTelFijo(String telFijo) {
		firePropertyChange("telFijo", this.telFijo, telFijo);
		this.telFijo = telFijo;
	}

	public String getTelMovil() {
		return this.telMovil;
	}

	public void setTelMovil(String telMovil) {
		firePropertyChange("telMovil", this.telMovil, telMovil);
		this.telMovil = telMovil;
	}

	public String getTelMovil2() {
		return this.telMovil2;
	}

	public void setTelMovil2(String telMovil2) {
		firePropertyChange("telMovil2", this.telMovil2, telMovil2);
		this.telMovil2 = telMovil2;
	}

	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		firePropertyChange("EMail", this.EMail, EMail);
		this.EMail = EMail;
	}

	public String getNombreTutor() {
		return this.nombreTutor;
	}

	public void setNombreTutor(String nombreTutor) {
		firePropertyChange("nombreTutor", this.nombreTutor, nombreTutor);
		this.nombreTutor = nombreTutor;
	}

	public String getApellidosTutor() {
		return this.apellidosTutor;
	}

	public void setApellidosTutor(String apellidosTutor) {
		firePropertyChange("apellidosTutor", this.apellidosTutor, apellidosTutor);
		this.apellidosTutor = apellidosTutor;
	}

	public String getNiftutor() {
		return this.niftutor;
	}

	public void setNiftutor(String niftutor) {
		firePropertyChange("niftutor", this.niftutor, niftutor);
		this.niftutor = niftutor;
	}

	public Date getFAlta() {
		return this.FAlta;
	}

	public void setFAlta(Date FAlta) {
		firePropertyChange("FAlta", this.FAlta, FAlta);
		this.FAlta = FAlta;
	}

	public Date getFBaja() {
		return this.FBaja;
	}

	public void setFBaja(Date FBaja) {
		firePropertyChange("FBaja", this.FBaja, FBaja);
		this.FBaja = FBaja;
	}

	public String getBaja() {
		if (this.baja !=null)
			return this.baja;
		else
			return "N";
	}

	public void setBaja(String baja) {
		firePropertyChange("baja", this.baja, baja);
		this.baja = baja;
	}

	public String getIndExportado() {
		return this.indExportado;
	}

	public void setIndExportado(String indExportado) {
		firePropertyChange("indExportado", this.indExportado, indExportado);
		this.indExportado = indExportado;
	}

	public String getNotas() {
		return this.notas;
	}

	public void setNotas(String notas) {
		firePropertyChange("notas", this.notas, notas);
		this.notas = notas;
	}
	
    public Set getMatriculas() 
    { 
        return matriculas; 
    }  

    public void setMatriculas(Set matriculas) 
    { 
        this.matriculas = matriculas; 
    }  

    public void addLibro(Matricula matricula) 
    { 
        this.matriculas.add(matricula); 
    } 
    
    public String getEdad(){

        Calendar fechaNacimiento = Calendar.getInstance();
 
        Calendar fechaActual = Calendar.getInstance();
        int edad = 0;
        
        if (FNacimiento != null){
	        fechaNacimiento.setTime(FNacimiento);
	       
	        int año = fechaActual.get(Calendar.YEAR)- fechaNacimiento.get(Calendar.YEAR);
	        int mes =fechaActual.get(Calendar.MONTH)- fechaNacimiento.get(Calendar.MONTH);
	        int dia = fechaActual.get(Calendar.DATE)- fechaNacimiento.get(Calendar.DATE);
	        
	        log.debug("año: "+año+" mes: "+ mes+" dia: "+dia);
	        
	        if(mes<0 || (mes==0 && dia<0)){
	            año--;
	        }
	        
	        edad = año;
        }
        else
        	edad = 0;
        
        return Integer.toString(edad);
    	
    }
    
    public void setEdad(){
    	// No hacemos nada pues no hay atributo edad.
    }
    
    public List<Recibo> getRecibos(){
    	AlumnoHome ah = new AlumnoHome();
    	return ah.getRecibos(this);
    }
    
	

}
