package es.academia.modelo;

// Generated 21-jul-2014 23:03:01 by Hibernate Tools 3.4.0.CR1

/**
 * Aula generated by hbm2java
 */
public class Aula extends AbstractModelObject implements java.io.Serializable {

	private Integer idAula;
	private String descAula;

	public Aula() {
	}

	public Aula(String descAula) {
		this.descAula = descAula;
	}

	public Integer getIdAula() {
		return this.idAula;
	}

	public void setIdAula(Integer idAula) {
		firePropertyChange("idAula", this.idAula, idAula);
		this.idAula = idAula;
	}

	public String getDescAula() {
		return this.descAula;
	}

	public void setDescAula(String descAula) {
		firePropertyChange("descAula", this.descAula, descAula);
		this.descAula = descAula;
	}

	public boolean equals(Object aula){
		if (aula != null && aula instanceof Aula)
			if (((Aula)aula).getIdAula()!= null &&
			    ((Aula)aula).getIdAula().intValue()== this.idAula.intValue())
				return true;
			else
				return false;
		else
			return false;
	}
	

}
