package es.academia.modelo;

// Generated 21-jul-2014 23:03:01 by Hibernate Tools 3.4.0.CR1

/**
 * Conocimiento generated by hbm2java
 */
public class Conocimiento implements java.io.Serializable {

	private Integer idConocimiento;
	private String descripcion;

	public Conocimiento() {
	}

	public Conocimiento(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getIdConocimiento() {
		return this.idConocimiento;
	}

	public void setIdConocimiento(Integer idConocimiento) {
		this.idConocimiento = idConocimiento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
/*	
	public String toString(){
		return getDescripcion();
	}
*/
}
