package es.academia.modelo;

// Generated 21-jul-2014 23:03:01 by Hibernate Tools 3.4.0.CR1

/**
 * DatosAcademia generated by hbm2java
 */
public class DatosAcademia implements java.io.Serializable {

	private Integer idDatosAcademia;
	private String nombreAcademia;
	private String denomFiscal;
	private String nif;
	private String direccion;
	private String poblacion;
	private String numCuenta;

	public DatosAcademia() {
	}

	public DatosAcademia(String nombreAcademia, String denomFiscal, String nif,
			String direccion, String poblacion, String numCuenta) {
		this.nombreAcademia = nombreAcademia;
		this.denomFiscal = denomFiscal;
		this.nif = nif;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.numCuenta = numCuenta;
	}

	public Integer getIdDatosAcademia() {
		return this.idDatosAcademia;
	}

	public void setIdDatosAcademia(Integer idDatosAcademia) {
		this.idDatosAcademia = idDatosAcademia;
	}

	public String getNombreAcademia() {
		return this.nombreAcademia;
	}

	public void setNombreAcademia(String nombreAcademia) {
		this.nombreAcademia = nombreAcademia;
	}

	public String getDenomFiscal() {
		return this.denomFiscal;
	}

	public void setDenomFiscal(String denomFiscal) {
		this.denomFiscal = denomFiscal;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getNumCuenta() {
		return this.numCuenta;
	}

	public void setNumCuenta(String numCuenta) {
		this.numCuenta = numCuenta;
	}

}
