package es.academia.modelo;

// Generated 21-jul-2014 23:03:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * FacturaRecibida generated by hbm2java
 */
public class FacturaRecibida implements java.io.Serializable {

	private Integer idFactura;
	private String descFactura;
	private Date FFactura;
	private String emisor;
	private BigDecimal importe;
	private int idTrContab;

	public FacturaRecibida() {
	}

	public FacturaRecibida(Date FFactura, BigDecimal importe, int idTrContab) {
		this.FFactura = FFactura;
		this.importe = importe;
		this.idTrContab = idTrContab;
	}

	public FacturaRecibida(String descFactura, Date FFactura, String emisor,
			BigDecimal importe, int idTrContab) {
		this.descFactura = descFactura;
		this.FFactura = FFactura;
		this.emisor = emisor;
		this.importe = importe;
		this.idTrContab = idTrContab;
	}

	public Integer getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(Integer idFactura) {
		this.idFactura = idFactura;
	}

	public String getDescFactura() {
		return this.descFactura;
	}

	public void setDescFactura(String descFactura) {
		this.descFactura = descFactura;
	}

	public Date getFFactura() {
		return this.FFactura;
	}

	public void setFFactura(Date FFactura) {
		this.FFactura = FFactura;
	}

	public String getEmisor() {
		return this.emisor;
	}

	public void setEmisor(String emisor) {
		this.emisor = emisor;
	}

	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	public int getIdTrContab() {
		return this.idTrContab;
	}

	public void setIdTrContab(int idTrContab) {
		this.idTrContab = idTrContab;
	}

}
