package es.academia.modelo;

// Generated 21-jul-2014 23:03:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Matricula generated by hbm2java
 */
public class Matricula extends AbstractModelObject implements java.io.Serializable {

	private Integer idMatricula;
//	private int idAlumno;
//	private int idCurso;
	private Date FDesde;
	private Date FHasta;
	private Date fecUltReciboGen;
	private BigDecimal pmatricula;
	private BigDecimal impMes;
	private BigDecimal impHora;
	private Integer horasDefecto;
	private BigDecimal descuento;
	private Alumno alumno;
	private Curso curso;
	private Set<Recibo> recibos = new HashSet<Recibo>();  

	public Matricula() {
	}
/*
	public Matricula(int idAlumno, int idCurso) {
		this.idAlumno = idAlumno;
		this.idCurso = idCurso;
	}
*/
	public Matricula( Date FDesde, Date FHasta,
			Date fecUltReciboGen, BigDecimal pmatricula, BigDecimal impMes,
			BigDecimal impHora, Integer horasDefecto, BigDecimal descuento) {
//		this.idAlumno = idAlumno;
//		this.idCurso = idCurso;
		this.FDesde = FDesde;
		this.FHasta = FHasta;
		this.fecUltReciboGen = fecUltReciboGen;
		this.pmatricula = pmatricula;
		this.impMes = impMes;
		this.impHora = impHora;
		this.horasDefecto = horasDefecto;
		this.descuento = descuento;
	}

	public Integer getIdMatricula() {
		return this.idMatricula;
	}

	public void setIdMatricula(Integer idMatricula) {
		firePropertyChange("idMatricula", this.idMatricula, idMatricula);
		this.idMatricula = idMatricula;
	}
/*
	public int getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(int idAlumno) {
		firePropertyChange("idAlumno", this.idAlumno, idAlumno);
		this.idAlumno = idAlumno;
	}

	public int getIdCurso() {
		return this.idCurso;
	}

	public void setIdCurso(int idCurso) {
		firePropertyChange("idCurso", this.idCurso, idCurso);
		this.idCurso = idCurso;
	}
*/
	public Date getFDesde() {
		return this.FDesde;
	}

	public void setFDesde(Date FDesde) {
		firePropertyChange("FDesde", this.FDesde, FDesde);
		this.FDesde = FDesde;
	}

	public Date getFHasta() {
		return this.FHasta;
	}

	public void setFHasta(Date FHasta) {
		firePropertyChange("FHasta", this.FHasta, FHasta);
		this.FHasta = FHasta;
	}

	public Date getFecUltReciboGen() {
		return this.fecUltReciboGen;
	}

	public void setFecUltReciboGen(Date fecUltReciboGen) {
		firePropertyChange("fecUltReciboGen", this.fecUltReciboGen, fecUltReciboGen);
		this.fecUltReciboGen = fecUltReciboGen;
	}

	public BigDecimal getPmatricula() {
		return this.pmatricula;
	}

	public void setPmatricula(BigDecimal pmatricula) {
		firePropertyChange("pmatricula", this.pmatricula, pmatricula);
		this.pmatricula = pmatricula;
	}

	public BigDecimal getImpMes() {
		return this.impMes;
	}

	public void setImpMes(BigDecimal impMes) {
		firePropertyChange("impMes", this.impMes, impMes);
		this.impMes = impMes;
	}

	public BigDecimal getImpHora() {
		return this.impHora;
	}

	public void setImpHora(BigDecimal impHora) {
		firePropertyChange("impHora", this.impHora, impHora);
		this.impHora = impHora;
	}

	public Integer getHorasDefecto() {
		return this.horasDefecto;
	}

	public void setHorasDefecto(Integer horasDefecto) {
		firePropertyChange("horasDefecto", this.horasDefecto, horasDefecto);
		this.horasDefecto = horasDefecto;
	}

	public BigDecimal getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigDecimal descuento) {
		firePropertyChange("descuento", this.descuento, descuento);
		this.descuento = descuento;
	}

	public Alumno getAlumno() {
		return alumno;
	}

	public void setAlumno(Alumno alumno) {
		firePropertyChange("alumno", this.alumno, alumno);
		this.alumno = alumno;
	}

	public Curso getCurso() {
		return curso;
	}

	public void setCurso(Curso curso) {
		firePropertyChange("curso", this.curso, curso);
		this.curso = curso;
	}

	public Set<Recibo> getRecibos() {
		return recibos;
	}

	public void setRecibos(Set<Recibo> recibos) {
		this.recibos = recibos;
	}

    public void addRecibo(Recibo recibo) 
    { 
        this.recibos.add(recibo); 
    } 

    public String getNombreCurso(){
    	
    	return curso.getDescCurso();
    }
    
    public String getAgnoCurso(){
    	return curso.getAnnoCurso();
    }
}
