package es.academia.modelo;

// Generated 21-jul-2014 23:03:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import es.academia.widgets.DateAca;

/**
 * Recibo generated by hbm2java
 */
public class Recibo extends AbstractModelObject implements java.io.Serializable {

	public static final String ESTADOPENDIENTE = "P";
	public static final String ESTADOGENERADO = "G";
	public static final String ESTADOANULADO = "A";
	public static final String CONCEPTOFIJO = "Mensualidad de ";

	private Integer idRecibo;
	private int idMatricula;
	private Serierecibo idSerie;
	private Integer numRecibo;
	private String concepto;
	private DateAca FGeneracion;
	private DateAca FDesde;
	private DateAca FHasta;
	private BigDecimal impMes;
	private Integer numHoras;
	private BigDecimal precHora;
	private BigDecimal impHoras;
	private BigDecimal descuento;
	private BigDecimal impTotal;
	private BigDecimal impoDescuento;
	private BigDecimal impoTotalDescuento;
	private String pagado;
	private String indExportado;
	private Matricula matricula;
	private String estadoRecibo; 	
	
	public Recibo() {
	}
/*
	public Recibo(int idMatricula, int idSerie) {
		this.idMatricula = idMatricula;
		this.idSerie = idSerie;
	}
*/
	public Recibo(int idMatricula, Serierecibo idSerie, Integer numRecibo,
			String concepto, DateAca FGeneracion, DateAca FDesde, DateAca FHasta,
			BigDecimal impMes, Integer numHoras, BigDecimal precHora,
			BigDecimal impHoras, BigDecimal descuento, BigDecimal impTotal,
			String pagado, String indExportado) {
		this.idMatricula = idMatricula;
		this.idSerie = idSerie;
		this.numRecibo = numRecibo;
		this.concepto = concepto;
		this.FGeneracion = FGeneracion;
		this.FDesde = FDesde;
		this.FHasta = FHasta;
		this.impMes = impMes;
		this.numHoras = numHoras;
		this.precHora = precHora;
		this.impHoras = impHoras;
		this.descuento = descuento;
		this.impTotal = impTotal;
		this.pagado = pagado;
		this.indExportado = indExportado;
	}

	public Integer getIdRecibo() {
		return this.idRecibo;
	}

	public void setIdRecibo(Integer idRecibo) {
		firePropertyChange("idRecibo", this.idRecibo, idRecibo);
		this.idRecibo = idRecibo;
	}

	public int getIdMatricula() {
		return this.idMatricula;
	}

	public void setIdMatricula(int idMatricula) {
		firePropertyChange("idMatricula", this.idMatricula, idMatricula);
		this.idMatricula = idMatricula;
	}

	public Serierecibo getIdSerie() {
		return this.idSerie;
	}

	public void setIdSerie(Serierecibo idSerie) {
		firePropertyChange("idSerie", this.idSerie, idSerie);
		this.idSerie = idSerie;
	}
	
	public String getDescSerieRecibo(){
		return getIdSerie().getDescSerie();
	}
	
	public void setDescSerieRecibo(String serie){
		// No hacemos nada pues no tenemos el atributo.
	}

	public Integer getNumRecibo() {
		return this.numRecibo;
	}

	public void setNumRecibo(Integer numRecibo) {
		firePropertyChange("numRecibo", this.numRecibo, numRecibo);
		this.numRecibo = numRecibo;
	}

	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		firePropertyChange("concepto", this.concepto, concepto);
		this.concepto = concepto;
	}

	public DateAca getFGeneracion() {
		return this.FGeneracion;
	}

	public void setFGeneracion(Date FGeneracion) {
		DateAca tmp = new DateAca();
		if (FGeneracion != null)
			tmp.setTime(FGeneracion.getTime());
		
		firePropertyChange("FGeneracion", this.FGeneracion, tmp);
		//this.FGeneracion = FGeneracion;
		//this.FGeneracion = new DateAca();
		this.FGeneracion=tmp;
		
	}

	public DateAca getFDesde() {
		return this.FDesde;
	}

	public void setFDesde(Date FDesde) {
		DateAca tmp = new DateAca();
		if (FDesde != null)
			tmp.setTime(FDesde.getTime());
		firePropertyChange("FDesde", this.FDesde, tmp);
		//this.FDesde = FDesde;
		//this.FDesde = new DateAca();
		this.FDesde=tmp;
	}

	public DateAca getFHasta() {
		return this.FHasta;
	}

	public void setFHasta(Date FHasta) {
		DateAca tmp = new DateAca();
		if (FHasta != null)
			tmp.setTime(FHasta.getTime());
		firePropertyChange("FHasta", this.FHasta, tmp);
		//this.FHasta = FHasta;
	//	this.FHasta = new DateAca();
		this.FHasta=tmp;
	}

	public BigDecimal getImpMes() {
		return this.impMes;
	}

	public void setImpMes(BigDecimal impMes) {
		firePropertyChange("impMes", this.impMes, impMes);
		this.impMes = impMes;
	}

	public Integer getNumHoras() {
		return this.numHoras;
	}

	public void setNumHoras(Integer numHoras) {
		firePropertyChange("numHoras", this.numHoras, numHoras);
		this.numHoras = numHoras;
	}

	public BigDecimal getPrecHora() {
		return this.precHora;
	}

	public void setPrecHora(BigDecimal precHora) {
		firePropertyChange("precHora", this.precHora, precHora);
		this.precHora = precHora;
	}

	public BigDecimal getImpHoras() {
		return this.impHoras;
	}

	public void setImpHoras(BigDecimal impHoras) {
		firePropertyChange("impHoras", this.impHoras, impHoras);
		this.impHoras = impHoras;
	}

	public BigDecimal getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigDecimal descuento) {
		firePropertyChange("descuento", this.descuento, descuento);
		this.descuento = descuento;
	}

	public BigDecimal getImpTotal() {
		return this.impTotal;
	}

	public void setImpTotal(BigDecimal impTotal) {
		firePropertyChange("impTotal", this.impTotal, impTotal);
		this.impTotal = impTotal;
	}

	public String getPagado() {
		return this.pagado;
	}

	public void setPagado(String pagado) {
		firePropertyChange("pagado", this.pagado, pagado);
		this.pagado = pagado;
	}

	public String getIndExportado() {
//		if (this.indExportado.equalsIgnoreCase("S"))
//			return "Sí";
//		else 
//			return "No";
			
		return this.indExportado;
	}

	public void setIndExportado(String indExportado) {
		firePropertyChange("indExportado", this.indExportado, indExportado);
//		if (indExportado.equalsIgnoreCase("Sí"))
//			this.indExportado="S";
//		else
//			this.indExportado="N";
		
		this.indExportado = indExportado;
	}

	public Matricula getMatricula() {
		return matricula;
	}

	public void setMatricula(Matricula matricula) {
		firePropertyChange("matricula", this.matricula, matricula);
		this.matricula = matricula;
	}
	
	public String getNombreCurso(){
		return getMatricula().getCurso().getDescCurso();
	}

	public void setNombreCurso(){
		// No hacemos nada.
	}

	public String getEstadoRecibo() {
		return estadoRecibo;
	}

	public void setEstadoRecibo(String estadoRecibo) {
		firePropertyChange("estadoRecibo", this.estadoRecibo, estadoRecibo);
		this.estadoRecibo = estadoRecibo;
	}
	public BigDecimal getImpoDescuento() {
		return impoDescuento;
	}
	public void setImpoDescuento(BigDecimal impoDescuento) {
		this.impoDescuento = impoDescuento;
	}
	public BigDecimal getImpoTotalDescuento() {
		return impoTotalDescuento;
	}
	public void setImpoTotalDescuento(BigDecimal impoTotalDescuento) {
		this.impoTotalDescuento = impoTotalDescuento;
	}


}
