package es.academia.modelo;

// Generated 21-jul-2014 23:03:01 by Hibernate Tools 3.4.0.CR1

/**
 * Serierecibo generated by hbm2java
 */
public class Serierecibo extends AbstractModelObject implements java.io.Serializable {

	private Integer idSerie;
	private String descSerie;
	private int sigRecibo;
	private int sigFactura;
	private String defecto;

	public Serierecibo() {
	}

	public Serierecibo(String descSerie, int sigRecibo, int sigFactura) {
		this.descSerie = descSerie;
		this.sigRecibo = sigRecibo;
		this.sigFactura = sigFactura;
	}

	public Integer getIdSerie() {
		return this.idSerie;
	}

	public void setIdSerie(Integer idSerie) {
		firePropertyChange("idSerie", this.idSerie, idSerie);
		this.idSerie = idSerie;
	}

	public String getDescSerie() {
		return this.descSerie;
	}

	public void setDescSerie(String descSerie) {
		firePropertyChange("descSerie", this.descSerie, descSerie);
		this.descSerie = descSerie;
	}

	public int getSigRecibo() {
		return this.sigRecibo;
	}

	public void setSigRecibo(int sigRecibo) {
		firePropertyChange("sigRecibo", this.sigRecibo, sigRecibo);
		this.sigRecibo = sigRecibo;
	}

	public int getSigFactura() {
		return this.sigFactura;
	}

	public void setSigFactura(int sigFactura) {
		firePropertyChange("sigFactura", this.sigFactura, sigFactura);
		this.sigFactura = sigFactura;
	}

	public String getDefecto() {
		return defecto;
	}

	public void setDefecto(String defecto) {
		this.defecto = defecto;
	}

}
