package es.academia.modelo;

// Generated 21-jul-2014 23:03:01 by Hibernate Tools 3.4.0.CR1

/**
 * Trcontab generated by hbm2java
 */
public class Trcontab implements java.io.Serializable {

	private Integer idTrContab;
	private String cuentaContable;
	private String desCuenta;

	public Trcontab() {
	}

	public Trcontab(String cuentaContable) {
		this.cuentaContable = cuentaContable;
	}

	public Trcontab(String cuentaContable, String desCuenta) {
		this.cuentaContable = cuentaContable;
		this.desCuenta = desCuenta;
	}

	public Integer getIdTrContab() {
		return this.idTrContab;
	}

	public void setIdTrContab(Integer idTrContab) {
		this.idTrContab = idTrContab;
	}

	public String getCuentaContable() {
		return this.cuentaContable;
	}

	public void setCuentaContable(String cuentaContable) {
		this.cuentaContable = cuentaContable;
	}

	public String getDesCuenta() {
		return this.desCuenta;
	}

	public void setDesCuenta(String desCuenta) {
		this.desCuenta = desCuenta;
	}

}
